### ISSUE TITLE
Official detailed User Guide

### ISSUE THREAD

**Issue by dPys** [dPys/PyNets#110]
* PyNets version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Oblivion83** [comment]
Here's the ls of /home/oblivion/coords_power_2011:

"10004_b'Power 2011 atlas'_Default_func_adj_mat_sps_0.3_4_network.png"   10004_Default_est_sps_unthresholded_mat.npy   10004_Default_net_metrics_sps_0.3_4_neat.csv   index.html
"10004_b'Power 2011 atlas'_sps_Default_0.3_4_func_glass_viz.png"         10004_Default_fdg_sps_network.js              10004_Default_wb_net_ts.npy                    labelnames_plotting.pkl
 10004_Default_connectogram_sps_network.js                               10004_Default_fdg_sps_network.json            coords_plotting.pkl                            net_metric_list_Default
 10004_Default_connectogram_sps_network.json                             10004_Default_net_metrics_sps_0.3_4           Default_func_coords_rsn.pkl
 10004_Default_est_sps_0.3_4.npy                                         10004_Default_net_metrics_sps_0.3_4.csv       Default_func_labelnames_rsn.pkl
_________________________________________________________________________________

Ok so I set the pickle_path to '/home/oblivion/coords_power_2011/coords_plotting.pkl' (as a test) and python didn't object. :)

Actually in the above folder, I noticed some CSV files like "10004_Default_net_metrics_sps_0.3_4.csv ", I'm guessing those are the outputs I will want play with? If so, is this bit:

import glob
import os
import pandas as pd
###
working_path = r'/work/04171/dpisner/data/ABM/network_analysis/' # use your path
name_of_network_pickle = 'net_metrics_sps_Default_mean'
###

allFiles = []
for ID in os.listdir(working_path):
    path_name = working_path + ID + '/' + ID + '_' + name_of_network_pickle
    if os.path.isfile(path_name):
        print(path_name)
        allFiles.append(path_name)

frame = pd.DataFrame()
list_ = []

for file_ in allFiles:
    df = pd.read_pickle(file_)
    node_cols = [s for s in list(df.columns) if isinstance(s, int) or any(c.isdigit() for c in s)]
    list_.append(df)

frame = pd.concat(list_)

out_path = working_path + '/' + name_of_network_pickle + '_output.csv'
frame.to_csv(out_path)


..............................no longer necessary?

Thanks so much for responding!

**Comment by dPys** [comment]
You're welcome! That bit is for concatenating all of the graph measures generated for the individual subjects into a group database :) So you will want to set the name_of_network_pickle = to 10004_Default_net_metrics_sps_0.3_4_neat.csv and your working_path to /home/oblivion/coords_power_2011 to run it. :)

**Comment by Oblivion83** [comment]
Tried: 
import pandas as pd
Backend TkAgg is interactive backend. Turning interactive mode on.
pickle_path = '/home/oblivion/coords_power_2011/coords_plotting.pkl'
df = pd.read_pickle(pickle_path)
df
[(-16, 28, 52), (48, 35, -12), (-2, 41, 16), (11, -53, 16), (-2, 25, 43), (2, -23, 30), (-2, -35, 30), (-34, 55, 3), (-2, -37, 43), (-25, -39, -7), (-45, -60, 21), (-20, 44, 39), (27, 16, -16), (-6, 50, -1), (-43, -64, 34), (50, -28, -3), (-34, 19, 50), (52, -1, -16), (52, 7, -30), (-2, 44, -8), (-68, -23, -16), (-6, -55, 26), (-6, 48, 23), (22, 32, 48), (55, -43, 21), (34, 37, -12), (-2, 37, 35), (-48, 25, -1), (-20, -21, -19), (6, 41, -5), (6, -48, 30), (-45, 30, -12), (0, 30, 26), (9, 53, 3), (52, 32, 1), (-55, -12, -10), (-57, -30, -3), (-2, -48, 12), (6, 48, -14), (-27, 52, 21), (6, -59, 34), (11, 35, 19), (-52, 3, -26), (-11, -55, 16), (55, -44, 37), (22, 39, 39), (6, 53, 16), (52, -59, 35), (64, -12, -19), (-11, 44, 7), (34, 16, -7)]
import glob
import os
import pandas as pd
name_of_network_pickle = '10004_Default_net_metrics_sps_0.3_4_neat.csv'
working_path = '/home/oblivion/coords_power_2011'
allFiles = []
for ID in os.listdir(working_path):
    path_name = working_path + ID + '/' + ID + '_' + name_of_network_pickle
    if os.path.isfile(path_name):
        print(path_name)
        allFiles.append(path_name)
frame = pd.DataFrame()
list_ = []
for file_ in allFiles:
    df = pd.read_pickle(file_)
    node_cols = [s for s in list(df.columns) if isinstance(s, int) or any(c.isdigit() for c in s)]
    list_.append(df)
frame = pd.concat(list_)
out_path = working_path + '/' + name_of_network_pickle + '_output.csv'
frame.to_csv(out_path)

.....and got: 

  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 16, in <module>
  File "/home/oblivion/.local/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 225, in concat
    copy=copy, sort=sort)
  File "/home/oblivion/.local/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
_______________________________________________________________________________

Did I choose the right pickle_path?

**Comment by dPys** [comment]
So, you are currently trying to average with the coordinates of the graph...

You will want to set name_of_network_pickle = 'Default_net_metrics_sps'

**Comment by Oblivion83** [comment]
Nope, still didn't work, I even tried changing the pickle path to use other .pkl files, and still getting the same error :(

Really sorry about taking up so much of your time.

**Comment by dPys** [comment]
Hi @Oblivion83 
Please send your revised code.

-Derek

**Comment by dPys** [comment]
Yes, it is normal for example C is to take a long time, particularly if you are not running on HPC, because you are essentially iterating the pipeline across two different RSNs (Default & Cont) at 5 different thresholds, and therefore generating 10 different models. If you wish to restrict CPU/memory resources so that your PC doesn't lag, you can try adding the -pm 1,2 flag which will restrict the workflow to using only 1 core and 2 gb of RAM. Note that if you do this, the workflow will take longer to run. Also note that to perform any clustering with the workflow (see example D), it will minimally require 2 cores and 4 gb of RAM.

Finally, if you wish to plot/visualize the results, you just need to add the -plt flag to the command-line call. 

derek;

**Comment by Oblivion83** [comment]
Hi Derek could I have your email address?

I'm actually new to all aspects of programming, and my new supervisor is making me learn by using PyNets. I'd like to continue our correspondence via e-mail, if its ok with you.

-Kavi

**Comment by dPys** [comment]
dpisner at utexas dot edu
