### ISSUE TITLE
Node Outside BrainMask

### ISSUE THREAD

**Issue by kimberlylray** [dPys/PyNets#145]
* PyNets version:
* Python version:
* Operating System:

### Description

Im running a graph analysis using resting state data thats been preprocessed via fMRIprep.
It looks like the brain mask I used excluded one of the nodes in the Power 2011 atlas, which then made the entire thing crash. 
Should I not include a brain mask?  If I don't, then I run the risk of including nodes that don't provide a reliable signal in my analysis.
It might be helpful if PyNets can identify which nodes are outside of the brain mask and give a warning, but still move forward with extracting the signal from remaining nodes.

### What I Did
I used this command: singularity exec /work/04171/dpisner/pynets_singularity_latest-2018-11-19-60e143007b19.img pynets_run.py -i /scratch/05231/klray/R33/fmriprep/sub-10035/ses-01/func/sub-10035_ses-01_task-REST_run-01_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz -id 10035 -a coords_dosenbach_2010,coords_power_2011 -ua /scratch/05231/klray/Schaefer2018_400Parcels_7Networks_order_FSLMNI152_2mm.nii -min_thr 0.05 -max_thr 0.25 -step_thr 0.05 -dt -mod partcorr,corr,sps -ns 3,6 -sm 0,2 -b 5 -pm 40,48 -plug LegacyMultiProc -m /scratch/05231/klray/R33/fmriprep/sub-10035/ses-01/func/sub-10035_ses-01_task-REST_run-01_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz -conf /scratch/05231/klray/R33/fmriprep/confounds_KLR/sub-10035_ses-01_task-REST_desc-confounds_regressorsKLR.txt
I attached the crash files. 
Thanks!
[crash-20181127-210728-klray-extract_ts_node.cI.c09.d1-5d4dc546-b4af-4411-826f-ebed91090adf.txt](https://github.com/dPys/PyNets/files/2622007/crash-20181127-210728-klray-extract_ts_node.cI.c09.d1-5d4dc546-b4af-4411-826f-ebed91090adf.txt)
[crash-20181127-211002-klray-extract_ts_node.cI.c06.d1-06905307-db94-4619-9e3a-cd1ae64c31af.txt](https://github.com/dPys/PyNets/files/2622008/crash-20181127-211002-klray-extract_ts_node.cI.c06.d1-06905307-db94-4619-9e3a-cd1ae64c31af.txt)
[crash-20181127-211002-klray-extract_ts_node.cI.c08.d1-f06930f1-da2f-4de6-9ed8-25218aacb46c.txt](https://github.com/dPys/PyNets/files/2622009/crash-20181127-211002-klray-extract_ts_node.cI.c08.d1-f06930f1-da2f-4de6-9ed8-25218aacb46c.txt)
[crash-20181127-211004-klray-extract_ts_node.cI.c04.d1-4531a55c-c99f-4d19-a485-fa6dc774dbce.txt](https://github.com/dPys/PyNets/files/2622010/crash-20181127-211004-klray-extract_ts_node.cI.c04.d1-4531a55c-c99f-4d19-a485-fa6dc774dbce.txt)
[crash-20181127-211010-klray-extract_ts_node.cI.c02.d1-92879a84-a328-4133-8194-e84aeaaad004.txt](https://github.com/dPys/PyNets/files/2622011/crash-20181127-211010-klray-extract_ts_node.cI.c02.d1-92879a84-a328-4133-8194-e84aeaaad004.txt)
[crash-20181127-211010-klray-extract_ts_node.cI.c03.d1-0f21b772-0da9-4212-8713-45643d0736cc.txt](https://github.com/dPys/PyNets/files/2622012/crash-20181127-211010-klray-extract_ts_node.cI.c03.d1-0f21b772-0da9-4212-8713-45643d0736cc.txt)
[crash-20181127-211010-klray-extract_ts_node.cI.c05.d1-287663e2-9256-4806-99b4-9dd25726012b.txt](https://github.com/dPys/PyNets/files/2622013/crash-20181127-211010-klray-extract_ts_node.cI.c05.d1-287663e2-9256-4806-99b4-9dd25726012b.txt)
[crash-20181127-211014-klray-extract_ts_node.cI.c01.d1-8f2e0eb5-b4e4-4d56-93c3-99650a0d993d.txt](https://github.com/dPys/PyNets/files/2622014/crash-20181127-211014-klray-extract_ts_node.cI.c01.d1-8f2e0eb5-b4e4-4d56-93c3-99650a0d993d.txt)
[crash-20181127-211025-klray-extract_ts_node.cI.c00.d1-eabe4d56-5372-4d3c-8123-a700e1f2924c.txt](https://github.com/dPys/PyNets/files/2622015/crash-20181127-211025-klray-extract_ts_node.cI.c00.d1-eabe4d56-5372-4d3c-8123-a700e1f2924c.txt)

**Comment by dPys** [comment]
Updates pushed. Please confirm that you are using pynets version 0.7.31! If the error goes away please let me know and I can close this issue :)
