### ISSUE TITLE
ward clustering based on AAL atlas 

### ISSUE THREAD

**Issue by rickwith** [dPys/PyNets#149]
Hi,
  Recently i am trying to do ward clustering based on AAL atlas on resting fMRI data, just like the article in https://www.ncbi.nlm.nih.gov/pubmed/24647227, i used nilearn but i found it cannot provide a "cutoff" option to get a total cluster number for all 116 rois, so i hope there is someone could share his script if someone have done the similar thing.

**Comment by dPys** [comment]
Hi @rickwith 

This is actually an open question with both nilearn and pynets. No clear sense yet on a timeline for accomplishing a new api for ward clustering in nilearn, but I might ask why not try just using ncut or kmeans in the meantime (or instead)?

@dPys

**Comment by rickwith** [comment]
Hi @dPys 

Thanks for your reply!
I indeed tried ncut method to do the power-law fit, but the results is not rather good, so i wanna do the same clustering step based on an atlas which was done in that plos one article. I used scipy to do ward clustering on each roi matrix, and the results is not good either for the fitting of power-law. The main purpose of this is found a mark that could discriminate UWS(unresponsive wakefulness syndrome) and healthy individual on rs-fMRI data. Do you have any suggestion about this?

**Comment by dPys** [comment]
Hi @rickwith 

I am not sure that I do have a better solution for you. Out of curiosity, how are you using ncut? Also, what metric are you using to define "good" results?

@dPys

**Comment by dPys** [comment]
Hi @rickwith -- sorry for the delayed reply. Sounds like a nilearn question to me!
