### ISSUE TITLE
ModuleNotFoundError: No module named 'dipy.tracking.local'

### ISSUE THREAD

**Issue by VasudevDevulapally** [dPys/PyNets#178]
* PyNets version:lates
* Python version : 3.6
* Operating System: Ubuntu 18.04

### Description

When i try to run the pynets, i am getting a dipy.tracking.local ModuleNotFoundError , and for the past 5 hours the program is tuck

### What I Did
Following is the command line call that i have used to run pynets_run.py 
```
Paste the command(s) you ran and the output.
pynets_run.py -dwi '/sk-home/vasudev/Music/Subjects/KON11/KON11/dwi-ec.nii.gz' -bval '/sk-home/vasudev/Music/Subjects/KON11/KON11/bvals' -bvec '/sk-home/vasudev/Music/Subjects/KON11/KON11/bvecs' -id KON11 -a atlas_destrieux_2009 -parc -tt 'particle' -dg 'boot' -mod 'csd' 'tensor' -anat '/sk-home/vasudev/Music/Subjects/KON11/KON11/KON11/KON11_t1_brain.nii.gz' -s 1000000 -dt -min_thr 0.05 -max_thr 0.10 -step_thr 0.01 -p 1

If there was a crash, please include the traceback here.
```
Traceback (most recent call last):
  File "/sk-home/vasudev/.local/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/sk-home/vasudev/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/sk-home/vasudev/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/sk-home/vasudev/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/sk-home/vasudev/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/sk-home/vasudev/.local/lib/python3.6/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 80, in run_track
  File "/sk-home/vasudev/.local/lib/python3.6/site-packages/pynets/dmri/track.py", line 57, in prep_tissues
    from dipy.tracking.local import ActTissueClassifier, CmcTissueClassifier, BinaryTissueClassifier
ModuleNotFoundError: No module named 'dipy.tracking.local'

**Comment by dPys** [comment]
Hi @VasudevDevulapally 

Thanks for reporting. This error was due to the latest [upgrades](https://github.com/nipy/dipy/blob/a5d66dd09f4dc7f0e0bb750d08c63d2dfa57b728/doc/api_changes.rst) to dipy 1.0.0 API. 

I am 99% positive that I've update all of the pynets bindings to correct these issues now. To fix, please:

1. uninstall pynets, 
2. reinstall pynets (from pip or from a fresh git clone https://github.com/dPys/PyNets.git and then run setup.py install). 
3. Then confirm you are using version 0.4.79 from the command-line with: python -c "import pynets; print(pynets.__version__)"
4. Re-run your pynets_run command.

If the issues are resolve, please let me know.

@dPys

**Comment by VasudevDevulapally** [comment]
@dPys  How can i uninstall pynets, sudo apt-get remove pynets does not work.

**Comment by dPys** [comment]
Hi @VasudevDevulapally ,

PyNets is not an aptitude package-- it is a python package. Since it is part of the pypi repository, you can just `pip uninstall pynets` or `sudo pip uninstall pynets`

**Comment by dPys** [comment]
Closing this issue for now since this issue should now be fixed, but please feel free to re-open if you continue to encounter errors. Thanks again for reporting!

@dPys
