### ISSUE TITLE
UnboundLocalError: local variable 'multimodal' referenced before assignment

### ISSUE THREAD

**Issue by egyptdj** [dPys/PyNets#193]
* PyNets version: release
* Python version: python 3.6.8
* Operating System: linux ubuntu 18.04

### Description

Dear pynets developers,
I installed the pynets with the Docker container and tried to run the example A) of Quickstart from the latest documentation (https://buildmedia.readthedocs.org/media/pdf/pynets/latest/pynets.pdf page 13). Following UnboundLocalError was returned.

`UnboundLocalError: local variable 'multimodal' referenced before assignment`

### What I Did

1> installed the pynets with the docker
`docker build -t pynets .`

2> ran the container
`sudo docker run -ti --rm --privileged -v /tmp:/tmp -v /var/tmp:/var/tmp pynets -func '/home/bispl/test/sub-A00000300_ses-20110101_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz' -id 'test' -mod 'partcorr' -thr 0.20 -m '/home/bispl/test/sub-A00000300_ses-20110101_task-rest_bold_space-MNI152NLin2009cAsym_brainmask.nii.gz'`

and the error was thrown as below

------------------------------------------------------------------------

Running workflow across single subject:
test

Using whole-brain pipeline...

Using node size of: 4mm...

Using connectivity model:
partcorr

Running functional connectometry only...
Functional file: /home/bispl/test/sub-A00000300_ses-20110101_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz

-------------------------------------------------------------------------

Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pynets/pynets_run.py", line 1585, in build_workflow
    directget, tiss_class, runtime_dict, embed, multi_directget, multimodal)
UnboundLocalError: local variable 'multimodal' referenced before assignment

WARNING: Upgrade to python3 for forkserver functionality...

------------------------------------------------------------------------

Running workflow across single subject:
test

Using whole-brain pipeline...

Using node size of: 4mm...

Using connectivity model:
partcorr

Running functional connectometry only...
Functional file: /home/bispl/test/sub-A00000300_ses-20110101_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz

-------------------------------------------------------------------------

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pynets/pynets_run.py", line 1690, in main
    sys.exit(p.exitcode)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pynets/pynets_run.py", line 1701, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/pynets/pynets_run.py", line 1694, in main
    build_workflow(args, retval)
  File "/opt/conda/lib/python3.6/site-packages/pynets/pynets_run.py", line 1585, in build_workflow
    directget, tiss_class, runtime_dict, embed, multi_directget, multimodal)
UnboundLocalError: local variable 'multimodal' referenced before assignment

---

I tried to go through the documentation thoroughly and concluded that this was not related to some build failures or passing the wrong options.
Thank you for your help, and your effort on developing the package.

Byung-Hoon

**Comment by dPys** [comment]
Hi Byung-Hoon,

Your command actually looks completely correct. The issue appears to be that the latest version of pynets listed on pypi (and which installs by default in the docker container) is 0.7.39, despite the actual latest version being 0.4.88 (some 50 versions ahead!)

Please either 1) rebuild from the latest Dockerfile, 2) run pip install pynets==0.4.88, or install via git clone and running python setup.py install.

Cheers,
@dPys

**Comment by egyptdj** [comment]
Hi @dPys ,

Thanks for the quick update.
I tried to rebuild the with the latest Dockerfile, but failed with the error:

```Installing collected packages: pyasn1, rsa, jmespath, python-dateutil, docutils, botocore, colorama, s3transfer, PyYAML, awscli, numpy, nibabel, pytz, pandas, scipy, docopt, num2words, patsy, bids-validator, sqlalchemy, pybids, boto3, h5py, dipy, pillow, PyWavelets, pyparsing, cycler, kiwisolver, matplotlib, networkx, imageio, scikit-image
Successfully installed PyWavelets-1.0.3 PyYAML-5.1.2 awscli-1.16.244 bids-validator-1.2.4 boto3-1.9.234 botocore-1.12.234 colorama-0.3.9 cycler-0.10.0 dipy-1.0.0 docopt-0.6.2 docutils-0.15.2 h5py-2.10.0 imageio-2.5.0 jmespath-0.9.4 kiwisolver-1.1.0 matplotlib-3.1.1 networkx-2.3 nibabel-2.5.1 num2words-0.5.10 numpy-1.17.2 pandas-0.25.1 patsy-0.5.1 pillow-6.1.0 pyasn1-0.4.7 pybids-0.9.4 pyparsing-2.4.2 python-dateutil-2.8.0 pytz-2019.2 rsa-3.4.2 s3transfer-0.2.1 scikit-image-0.15.0 scipy-1.3.1 sqlalchemy-1.3.8
Removing intermediate container db782556f020
 ---> 630759d00804
Step 19/44 : RUN git clone -b master https://github.com/dPys/PyNets PyNets &&     chmod 775 -R PyNets/*/*.py &&     cd PyNets &&     pip install -r requirements.txt &&     python setup.py install
 ---> Running in d2d27b25b45d
Cloning into 'PyNets'...
Downloading pynets/core/atlases/AAL2zourioMazoyer2002.nii.gz (61 KB)
Error downloading object: pynets/core/atlases/AAL2zourioMazoyer2002.nii.gz (5994255): Smudge error: Error downloading pynets/core/atlases/AAL2zourioMazoyer2002.nii.gz (5994255077ca625ee636fba27d9182fa2b4393cd0bbf9ddc5f10a2a62f85dbf5): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Errors logged to /home/neuro/PyNets/.git/lfs/logs/20190924T070818.099876676.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: pynets/core/atlases/AAL2zourioMazoyer2002.nii.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

The command '/bin/sh -c git clone -b master https://github.com/dPys/PyNets PyNets &&     chmod 775 -R PyNets/*/*.py &&     cd PyNets &&     pip install -r requirements.txt &&     python setup.py install' returned a non-zero code: 128```

Maybe the data quota is full now..
Thanks,
Byung-Hoon

**Comment by dPys** [comment]
Yes, @egyptdj -- data quota is full. Just refilled it.

Let me know if you continue to experience any issues,
@dPys

**Comment by egyptdj** [comment]
Thank you @dPys ,

I could rebuild the docker container with a bit of modification in the Dockerfile line 125:
`chmod -R 777 /data` to 
`chmod -R 777 /inputs`.

========

Sadly, the command is not working yet.
running the container

`sudo docker run -ti --rm --privileged -v /tmp:/tmp -v /var/tmp:/var/tmp pynets -func '/home/bispl/test/sub-A00000300_ses-20110101_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz' -id 'test' -mod 'partcorr' -thr 0.20 -m '/home/bispl/test/sub-A00000300_ses-20110101_task-rest_bold_space-MNI152NLin2009cAsym_brainmask.nii.gz'`

throws the following error:

> 190925-10:23:17,842 nipype.utils INFO:
> 	 Running nipype version 1.2.3 (latest: 1.2.3)
> 190925-10:23:19,212 nipype.utils INFO:
> 	 Running nipype version 1.2.3 (latest: 1.2.3)
> 
> 
> > ------------------------------------------------------------------------
> 
> Running workflow for single subject:
> test
> 
> Using whole-brain pipeline...
> 
> Using node size of: 4mm...
> 
> Using connectivity model: partcorr
> 
> Running fmri connectometry only...
> BOLD Image: /home/bispl/test/sub-A00000300_ses-20110101_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz
> 
> -------------------------------------------------------------------------
> 
> 
> /opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
>   warnings.warn(msg, category=DeprecationWarning)
> No connectivity model or time-series node extraction iterables...
> Single threshold...
> Multiple atlases...
> Running Unimodal Meta-Workflow...
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/pynets-0.9.0-py3.6.egg/EGG-INFO/scripts/pynets_run.py", line 1739, in build_workflow
>     os.mkdir("%s%s%s" % (func_dir, '/', base_dirname))
> FileNotFoundError: [Errno 2] No such file or directory: '/home/bispl/test/wf_single_subject_fmri_test'
> 
> WARNING: Forkserver failed to initialize. Are you using Python3 ?
> 
> 
> 
> ------------------------------------------------------------------------
> 
> Running workflow for single subject:
> test
> 
> Using whole-brain pipeline...
> 
> Using node size of: 4mm...
> 
> Using connectivity model: partcorr
> 
> Running fmri connectometry only...
> BOLD Image: /home/bispl/test/sub-A00000300_ses-20110101_task-rest_bold_space-MNI152NLin2009cAsym_preproc.nii.gz
> 
> -------------------------------------------------------------------------
> 
> 
> /opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
>   warnings.warn(msg, category=DeprecationWarning)
> No connectivity model or time-series node extraction iterables...
> Single threshold...
> Multiple atlases...
> Running Unimodal Meta-Workflow...
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/site-packages/pynets-0.9.0-py3.6.egg/EGG-INFO/scripts/pynets_run.py", line 1844, in main
>     sys.exit(p.exitcode)
> SystemExit: 1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/bin/pynets_run.py", line 4, in <module>
>     __import__('pkg_resources').run_script('pynets==0.9.0', 'pynets_run.py')
>   File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1462, in run_script
>     exec(code, namespace, namespace)
>   File "/opt/conda/lib/python3.6/site-packages/pynets-0.9.0-py3.6.egg/EGG-INFO/scripts/pynets_run.py", line 1855, in <module>
>     main()
>   File "/opt/conda/lib/python3.6/site-packages/pynets-0.9.0-py3.6.egg/EGG-INFO/scripts/pynets_run.py", line 1848, in main
>     build_workflow(args, retval)
>   File "/opt/conda/lib/python3.6/site-packages/pynets-0.9.0-py3.6.egg/EGG-INFO/scripts/pynets_run.py", line 1739, in build_workflow
>     os.mkdir("%s%s%s" % (func_dir, '/', base_dirname))
> FileNotFoundError: [Errno 2] No such file or directory: '/home/bispl/test/wf_single_subject_fmri_test'

I went through the pynets_run.py script, and couldn't come up with the reason for the os.mkdir function to raise such an error. (asserted that the '/home/bispl/test/' path existed so that it was not related to recursive creation of directories.)

Thanks for your help!

**Comment by dPys** [comment]
Please refer to docker documentation as it appears that you are calling a directory ('/home/bispl/test') that is not being mounted in the container, which is most certainly the source of the problem in this case.

@dPys

**Comment by egyptdj** [comment]
Got it. Closing this issue.
Thanks

@egyptdj
