### ISSUE TITLE
Enable thresholding for raw graph input

### ISSUE THREAD

**Issue by AKSoo** [dPys/PyNets#357]
https://github.com/dPys/PyNets/blob/ed82aed4dee64ac4c1b81315d5d6461a6803d40b/pynets/cli/pynets_run.py#L1009-L1011

Currently, threshold is always set to 0 for raw graph inputs. However, a user may want to threshold a raw weighted graph before analysis.

**Comment by dPys** [comment]
@AKSoo -- this is an excellent observation. I can work on this today. 

Cheers,
@dPys

**Comment by dPys** [comment]
Alright @AKSoo , try the prototype that does this on the dev branch:
```git clone https://github.com/dPys/PyNets.git -b development``` and ```python setup.py install```

then, with the `pynets` CLI, you can list any number of space-delimited graphs using the -g flag, and then use either `-thr {}` or `-min_thr {} -max_thr {} -step_thr {}`, but be sure to also include a subject identifier with the `-id {}` flag. Right now, this will run multiple graphs for a single subject, but it cannot do multiple subject ID's in a single CLI call. Let me know what you think!

@dPys

**Comment by dPys** [comment]
> https://github.com/dPys/PyNets/blob/ed82aed4dee64ac4c1b81315d5d6461a6803d40b/pynets/cli/pynets_run.py#L1009-L1011
> 
> Currently, threshold is always set to 0 for raw graph inputs. However, a user may want to threshold a raw weighted graph before analysis.

Also, please bear in mind that a threshold of 1.0 means NO thresholding will be applied. Please disregard that the default was set to 0 previously. The `-thr` flag refers to what percent of connections will be retained, not what percent will be removed.

**Comment by dPys** [comment]
I'm marking this issue as resolved. If you encounter any errors, please feel free to reopen!
