### ISSUE TITLE
Registering PyNets on brainlife.io

### ISSUE THREAD

**Issue by soichih** [dPys/PyNets#401]
Hi @dPys 

Thanks for the poster presentation during OHBM2020! I've been meaning to ask you and see if you might be interested in enabling this App on https://brainlife.io platform. I know there are already many ways to run PyNets, but brainlife can be yet another (easy?) way for someone to run PyNets - especially for folks who doesn't have access to any HCP resources. I think it would be great if people can run PyNets for fmri analysis.

Sorry for reaching out via github (I don't have your contact info!) Anyway, please let me know if you are interested.. and I can help you register the App. You can also email me at hayashis@iu.edu 

Cheers!

**Comment by dPys** [comment]
Awesome, yep thanks! brainlife.io seems like an excellent place for users to run PyNets. Will connect via DM and close this issue for now.

Cheers,
@dPys
